export const FETCH_SOURCES = 'FETCH_SOURCES';
export const FETCH_SOURCES_SUCCESS = 'FETCH_SOURCES_SUCCESS';
export const FETCH_SOURCES_ERROR = 'FETCH_SOURCES_ERROR';
export const CHANGE_SOURCES = 'CHANGE_SOURCES';

export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';
// export const CHANGE_ARTICLES = 'CHANGE_ARTICLES';
